"""update data type

Revision ID: 12dbffd71385
Revises: ee533bcb2b8c
Create Date: 2026-03-17 08:15:53.633035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dbffd71385'
down_revision = 'ee533bcb2b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('num_examination',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('num_examination',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
