"""add  are resived for save_for_exmnations table

Revision ID: 34747b224cd3
Revises: 9884aacd8be9
Create Date: 2026-04-06 18:25:52.764038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34747b224cd3'
down_revision = '9884aacd8be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save_for_exmnations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('are_received', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save_for_exmnations', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('are_received')

    # ### end Alembic commands ###
