"""initial migration

Revision ID: cafc0ed35071
Revises: 
Create Date: 2026-01-01 21:03:44.911780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafc0ed35071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic_branch', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
