"""add patient table

Revision ID: ee533bcb2b8c
Revises: cafc0ed35071
Create Date: 2026-03-14 00:12:20.506981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee533bcb2b8c'
down_revision = 'cafc0ed35071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_for_examination', sa.String(length=120), nullable=False),
    sa.Column('num_examination', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
